### ISSUE TITLE
No syntax highlighting at all

### ISSUE THREAD

**Issue by MaxGyver83** [mwgkgk/kmonad-vim#1]
Hello @mwgkgk,

thanks for sharing this plugin! I have tested it and didn't get any syntax highlighting at all. At least, the filetype of my config file was set to `kmonad`. Do I have to do anything else? This is the [config](https://github.com/MaxGyver83/dotfiles/blob/master/kmonad/.config/kmonad/vou-linux-de-rctrl.kbd) I used for testing this plugin.

I looked into the source code and saw that comments are expected to start with `//`. AFAIK, comments start with `;;` in KMonad config files. Maybe configuration files were different when you created this plugin?

**Comment by mwgkgk** [comment]
Correct, this plugin refers to an ancient version of Kmonad that had different syntax. I'm glad to see the project being actively worked on!

It's hard for me to say what exactly has changed since. Apparently it uses S-expressions now! Well that's a radical departure. From a look at the syntax you should be fine with setting filetype=lisp in `ftdetect/kmonad.vim`, like this:

```vim
augroup filetypedetect
  au BufRead,BufNewFile *.kbd setfiletype lisp
augroup END
```

I'll mark this repo as obsolete.

**Comment by MaxGyver83** [comment]
`setfiletype clojure` works even better. But luckily there is another KMonad plugin for vim: [KMonad.vim](https://git.hugoheagren.com/Hugo-Heagren/KMonad.vim) (It's self-hosted and not always online.)

See this KMonad issue about [Syntax highlighters for Emacs/Vim #69](https://github.com/david-janssen/kmonad/issues/69).
